### ISSUE TITLE
Install bundle like standart alfresco amp

### ISSUE THREAD

**Issue by TheElvenPath** [xenit-eu/dynamic-extensions-for-alfresco#162]
Hi, didn't find information about installing bundles on file system.
Could we install bundle like alfresco module amp?
With creating folders of module like: tomcat/webapp/platform/web-inf/classes/alfresco/module/installed-bundle-module?

I want to use standart alfresco bootstrap mechanism:
```xml
<bean id="enumeration.templates.spacesBootstrap" parent="spacesStoreImporter">
		<property name="useExistingStore">
			<value>true</value>
		</property>
		<property name="bootstrapViews">
			<list>
				<props>
					<prop key="uuidBinding">UPDATE_EXISTING</prop>
					<prop key="path">/</prop>
					<prop key="location">osgibundle:/META-INF/alfresco/module/letters-repo/bootstrap/enumeration-templates.xml</prop>
					<prop key="encoding">UTF-8</prop>
				</props>
			</list>
		</property>
	</bean>
```

Is any possible opportunity to do like this?

**Comment by stanmine** [comment]
Hello @TheElvenPath ,

You can deploy bundles with an amp. 
At the moment there is no build script (gradle/maven plugin) available to create an amp from your project, but it is not difficult to do this in your self.

To load bundles from the file system, they have to be present in `tomcat/webapps/alfresco/WEB-INF/classes/dynamic-extensions/bundles/`

Thus, your amp needs to have to following structure:
```
.
├── config
│   └── dynamic-extensions
│       └── bundles
│           └── my-de-bundle.jar
└── module.properties
```

You can create a gradle or maven task that copies your build artifact to this folder structure and then zips it.

Using the standard alfresco bootstrap mechanism is also possible. You can add needed beans and files to the same amp but in the correct directory (`/config/alfresco/module/...`). 

Some small notes.
When building your amp, make sure that all external dependencies that your bundle needs (the ones that are not by default in alfresco) are also in that folder. Otherwise your bundle will fail to start. 
It is also possible to override a bundle that is deployed on the filesystem through the dashboard. Keep in mind that if the alfresco restarts, the bundle of the file system is loaded again and not the bundle deployed afterwards.

**Comment by TheElvenPath** [comment]
@stanmine Thanks a lot. 
Another question: is possible to install bundle on filesystem though dashboard. With possibility to use standard alfresco bootstrap. (I only need to hot deploy this modules).

**Comment by stanmine** [comment]
Hello @TheElvenPath 

It is not possible to install a bundle on the filesystem through the dashboard. If you install a bundle through the dashboard, it is uploaded to Alfresco to the `Data Dictionary > Dynamic Extensions > Bundles` folder, but it is not copied to tomcat webapps directory.

If you want to use the standard alfresco bootstrap, you cannot do this part through the DE dashboard. You will have to do this the "official way" through an amp.  What is possible is that you create an amp with the alfresco bootstrap resources in it, and a bundle with your code. This way you can hotdeploy your code but not your bootstrap resources.

The `osgi.container.repository-bundles = false` should only disable bundles intalled through the dashboard, thus the bundles in the  `Data Dictionary > Dynamic Extensions > Bundles` folder`. Bundles located in the tomcat/webapps directory will always be loaded.

**Comment by TheElvenPath** [comment]
Hello @stanmine . I am return to that task.  Find out another problem. If i add spring context with at least one bean to ```resources/META-INF/spring/module-context.xml``` than not loading model from ```META-INF/alfresco/models``` because of NullPointerException in com.github.dynamicextensionsalfresco.models.RepositoryModelRegistrar - all @Authowired beans are null. If i remove xml configuration all works fine. Is any possible opportunity to use both - xml and annotation configuration?

**Comment by thijslemmens** [comment]
@TheElvenPath Can you make a separate issue for the bug you described?

**Comment by TheElvenPath** [comment]
@thijslemmens Done. [](https://github.com/xenit-eu/dynamic-extensions-for-alfresco/issues/164)

**Comment by yregaieg** [comment]
Closing as initial issue solved, and the new questions are ported to a new thread.
