### ISSUE TITLE
Breaking change in Static-Web url's

### ISSUE THREAD

**Issue by todorinskiz** [xenit-eu/dynamic-extensions-for-alfresco#181]
## I'm submitting a ...   (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] question
```

## Expected Behavior
Static-Web links starts with: `/com-github-dynamicextensionsalfresco-control-panel/web/`

## Current Behavior
Static-Web links starts with: `/alfresco-dynamic-extensions-repo-control-panel/web/`

## Context
After creating a new WAR for deployment, with the AMP-Modules Dynamic Extensions 1.7.1 the startup of the WAR fails.
Previously used configuration Alfresco Enterprise 4.2.7 and Dynamic Extensions 1.4.2.

Exception message:
```
2018-01-24 15:02:00,518 ERROR [org.eclipse.gemini.blueprint.extender.internal.activator.ContextLoaderListener] [localhost-startStop-1] Application context refresh failed (DynamicExtensionsApplicationContext(bundle=eu.xenit.de.control-panel, config=osgibundle:/META-INF/spring/*.xml))
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageConverterRegister': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.github.dynamicextensionsalfresco.webscripts.MessageConverterRegistry]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/http/converter/json/MappingJackson2HttpMessageConverter
```

## Your Environment
* DE version used: 1.4.2 until latest

## Attachments

![broken url](https://user-images.githubusercontent.com/6491638/38421228-b88155e2-39a6-11e8-981c-e2ed7cf12f54.png)

**Comment by stanmine** [comment]
@todorinskiz 
I think you are mixing 2 things up here.

The issue with the static-web links is due to a remaning of the artifactid in version 1.6.0.
However, the exception you mention has been fixed in version 1.7.2. See issue #160 for this.

Thus for fixing the exception, can you try your code with the latest DE version (1.7.4). 
As for the url's of the static web links, it might be good to get discussion going to see if we have to revert to the old link. Perhaps @tgeens can give some input here.

Stan
