### ISSUE TITLE
Architecture, Design Documentation for better understanding of internals?

### ISSUE THREAD

**Issue by gdeverlant** [xenit-eu/dynamic-extensions-for-alfresco#245]
## I'm submitting a ...   (check one with "x")
```
[ ] bug report
[ ] feature request
[X] question
```

I would like to know if there is any internal documents PDF, Videos showing visually the architecture of this project for us to better understand it or was this developed without anything. I'm not talking about the Wiki of this repo but more of important Spring to Alfresco to DE documentations. I'm now doing reverse engineering to understand this.

**Comment by kerkhofsd** [comment]
Hi @gdeverlant,
I'm afraid there currently is no such thing. 
The best resource in understanding the internals currently is the [video of the Barcelona Summit 2013](https://www.youtube.com/watch?v=Pc62PM7U3Ns).

Dynamic Extensions depends on some other technologies like OSGI and [Gemini Blueprint](https://www.eclipse.org/gemini/blueprint/). An understanding in these projects / technologies also helps understanding DE.

**Comment by gdeverlant** [comment]
Honestly the  video is not really helpful and it is sad that the architect did not put his ideas and thought process for us to be able to understand all the analysis he did to come up with that conclusion. This is really not good for the health of any project.

**Comment by tgeens** [comment]
Hey @gdeverlant 

You are still figuring out how development on the Alfresco platform works.  You should read up here: http://docs.alfresco.com/6.0/concepts/dev-platform-extension-points.html

This projects covers most common extension points and attempts to improve the developer-experience. 

As a user, I have used DE successfully for years, without understanding the internals. The wiki is a good place to get started - as a user, but it assumes you already know the Alfresco concepts.

The two original developers are not around anymore and we have picked up maintenance/ownership of the project since. That is not something that you can jump into, without first having a working understanding about Alfresco, Spring & OSGi.  Providing a knowledge base on these topics is not in the scope of this project.

If you have a practical problem with DE, we can probably have a look at your project and see how we can help.

**Comment by gdeverlant** [comment]
Well I've started to look into Alfresco documentation 1 week ago and I'm already understanding the basic concepts. Spring and OSGi are common technologies that I have used many time but it doesn't clear how to architecture of this plugin is working.

That's why I'm doing a step by step process to figure it out right now. I was thinking about using parts of the DE which are only related with blueprint & blueprint-integration and try to create an equivalent of this OSGi container for monolith Servlet based CMS like Magnolia.

I was thinking taking only some part of it and just make the blueprint and the OSGi container run first in Magnolia. Like in Alfresco with the AMP, Magnolia offers also a plugin architecture where the initialization process is working really similar.

It looks like the entry point of DE is **OsgiContainerModuleComponent** like it is mentioned in http://docs.alfresco.com/6.0/references/dev-extension-points-module-component.html
